version: "3.8"
services: 
    kitcon_balancer:
        container_name: "kitcon_balancer"
        image: nginx
        restart: "no"
        volumes:
          - $PWD/balancer/sites-enabled:/etc/nginx/sites-enabled
          - $PWD/balancer/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "80:80"
    
    kitcon_web:
        container_name: "kitcon_web"
        image: "node"
        env_file:
            - .env
        restart: "no"
        working_dir: "/mnt/project"
        volumes: 
            - $PWD/../kitcon-web:/mnt/project
            - $PWD/../kitcon-core:/mnt/kitcon-core
            - $PWD/../kitcon-ui:/mnt/kitcon-ui
            - $PWD/../kitcon-node:/mnt/kitcon-node

        command: ["npm", "start"]

    kitcon_redis:
        container_name: "kitcon_redis"
        image: "redis:alpine"
        restart: "no"
        ports: 
            - "6379:6379"

    kitcon_seo_service:
        container_name: "kitcon_seo_service"
        image: "node"
        restart: "no"
        working_dir: "/mnt/project"
        env_file:
            - .env
        volumes: 
            - $PWD/../kitcon-seo-service:/mnt/project
            - $PWD/../kitcon-core:/mnt/kitcon-core
            - $PWD/../kitcon-ui:/mnt/kitcon-ui
            - $PWD/../kitcon-node:/mnt/kitcon-node

        command: ["npm", "start"]