version: "3.8"
services:
  kitcon_balancer:
    container_name: "kitcon_balancer"
    image: nginx
    restart: "no"
    volumes:
      - $PWD/balancer/sites-enabled:/etc/nginx/sites-enabled
      - $PWD/balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - kitcon_seo_service
      - kitcon_web
      - kitcon_auth_service
    links:
      - kitcon_seo_service
      - kitcon_web
      - kitcon_auth_service

  kitcon_web:
    container_name: "kitcon_web"
    image: "node"
    env_file:
      - .env
    restart: "no"
    working_dir: "/mnt/project"
    volumes:
      - $PWD/../kitcon-web:/mnt/project
      - $PWD/../kitcon-core:/mnt/kitcon-core
      - $PWD/../kitcon-ui:/mnt/kitcon-ui
      - $PWD/../kitcon-node:/mnt/kitcon-node

    command: ["npm", "start"]

  kitcon_redis:
    container_name: "kitcon_redis"
    image: "redis:alpine"
    restart: "no"
    ports:
      - "6379:6379"

  kitcon_seo_service:
    container_name: "kitcon_seo_service"
    image: "node"
    restart: "no"
    working_dir: "/mnt/project"
    env_file:
      - .env
    volumes:
      - $PWD/../kitcon-seo-service:/mnt/project
      - $PWD/../kitcon-core:/mnt/kitcon-core
      - $PWD/../kitcon-ui:/mnt/kitcon-ui
      - $PWD/../kitcon-node:/mnt/kitcon-node
    command: ["npm", "start"]

  kitcon_auth_service:
    container_name: "kitcon_auth_service"
    image: "node"
    restart: "no"
    working_dir: "/mnt/project"
    env_file:
      - .env
    volumes:
      - $PWD/../kitcon-auth-service:/mnt/project
      - $PWD/jwtRS256.key:/mnt/keys/private.key
      - $PWD/jwtRS256.key.pub:/mnt/keys/public.key
      - $PWD/../kitcon-core:/mnt/kitcon-core
      - $PWD/../kitcon-ui:/mnt/kitcon-ui
      - $PWD/../kitcon-node:/mnt/kitcon-node
    depends_on:
      - wow_db_auth
    command: ["npm", "start"]

  wow_db_auth:
    container_name: "wow_db_auth"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: auth
    volumes:
      - $PWD/../../wow/env/.db_auth:/var/lib/mysql
    ports:
      - 3306:3306

  kitcon_php:
    build:
      context: .
      dockerfile: ./php.dockerfile
    env_file:
      - .env
    working_dir: "/mnt/project"
    volumes:
      - $PWD/../kitcon-php-helper:/mnt/project
