version: "3.8"
services: 
    kitcon_balancer:
        container_name: "kitcon_balancer"
        image: nginx
        restart: "no"
        volumes:
          - $PWD/balancer/sites-enabled:/etc/nginx/sites-enabled
          - $PWD/balancer/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "80:80"
    
    kitcon_web:
        container_name: "kitcon_web"
        image: "node"
        restart: "no"
        working_dir: "/mnt/project"
        volumes: 
            - $PWD/../kitcon-web:/mnt/project
            - $PWD/../kitcon-core:/mnt/project/kitcon/core
            - $PWD/../kitcon-ui:/mnt/project/kitcon/ui
            - $PWD/../kitcon-node:/mnt/project/kitcon/node

        command: ["npm", "start"]
    
    kitcon_libs:
        container_name: "kitcon_libs"
        image: "node"
        restart: "no"
        working_dir: "/mnt"
        volumes: 
            - $PWD/../kitcon-core:/mnt/core
            - $PWD/../kitcon-ui:/mnt/ui
            - $PWD/../kitcon-node:/mnt/node
        tty: true  